import Head from "next/head";
import AlertProvider from "../../components/context/AlertProvider";
import AuthLogin from "../../components/auth/AuthLogin";

export default function Login() {
  return (
    <>
      <Head>
        <title>Login | EntertainHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.png" />
      </Head>
      <AlertProvider>
        <AuthLogin />
      </AlertProvider>
    </>
  );
}
