import Head from "next/head";
import AlertProvider from "../../components/context/AlertProvider";
import AuthSignup from "../../components/auth/AuthSignup";

export default function Signup() {
  return (
    <>
      <Head>
        <title>Sign-up | EntertainHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.png" />
      </Head>
      <AlertProvider>
        <AuthSignup />
      </AlertProvider>
    </>
  );
}
