import Head from "next/head";
import { useShow } from "@/components/context/ShowProvider";
import Layout from "@/components/layout/Layout";
import MovieContainer from "@/components/movies/MovieContainer";
import ShowCard from "../../components/ShowCard";
import uuid from "react-uuid";

export default function Movies() {
  return (
    <>
      <Head>
        <title>Movies | EntertainHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.png" />
      </Head>
      <Layout>
        <MovieContainer />
      </Layout>
    </>
  );
}
