import Head from "next/head";
import Layout from "./components/layout/Layout";
import Trending from "./components/home/Trending";
import Recommendations from "./components/home/Recommendations";

export default function App() {
  return (
    <>
      <Head>
        <title>Home | EntertainHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.png" />
      </Head>
      <Layout>
        <div className="showListContainer ">
          <Trending />
          <Recommendations />
        </div>
      </Layout>
    </>
  );
}
